#!/usr/bin/env python
# -*- coding: utf-8 -*-

# dohvaćanje vanjskih funkcija
from os import environ as env
import keystoneclient.v2_0.client as ksclient
import glanceclient.v2.client as glclient
from credentials import get_creds

# instanciranje keystone objekta putem enviorment varijabli
keystone = ksclient.Client(**get_creds())

# dohvaćanje URL adrese glance API-ja
glance_endpoint = keystone.service_catalog.url_for(service_type='image')

# instanciranje glance objekta putem keystone usluga
glance = glclient.Client(glance_endpoint, token=keystone.auth_token)
 
nova.servers.create(name='minecraft-server', flavor=nova.flavors.find(name="m1.small"), image=nova.images.find(name="Ubuntu 14.04"), key_name="my_key")

print "Instance Created"
